java_test(
    name = "fancytext",
    srcs = glob(["**/*.java"]),
    test_class = "com.engflow.fancytext.FancyFormatterTest",
    deps = [
        "//src/java/com/engflow/fancytext",
        "@junit",
        "@truth",
    ],
)